version: 7.9.{build}
image: Visual Studio 2017

max_jobs: 1
clone_folder: c:\projects

environment:
  matrix:
    - platform: Win32
      archi: x86
      platform_input: Win32

configuration:
    - Unicode Debug

install:
    - if "%archi%" NEQ "" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - ps: |
          Write-Output "Configuration: $env:CONFIGURATION"
          Write-Output "Platform: $env:PLATFORM"
    
    - cd "%APPVEYOR_BUILD_FOLDER%"\PowerEditor\visual.net\
    - cov-build --dir cov-int msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform="%platform_input%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - 7z a cov.zip cov-int\*

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        $nppFileName = "Notepad++.$env:PLATFORM_INPUT.$env:CONFIGURATION.exe"

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Unicode Debug") {
            Push-AppveyorArtifact "PowerEditor\visual.net\Unicode Debug\Notepad++.exe" -FileName "$nppFileName"
        }

        Push-AppveyorArtifact "PowerEditor\visual.net\cov.zip" -FileName "cov.zip"

