version: 1.0.{build}
image: Visual Studio 2013

clone_depth: 1

platform:
    - Win32

configuration:
    - Unicode Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %archi%

build:
    verbosity: minimal

build_script:
    - cd c:\projects\notepad-plus-plus\PowerEditor\visual.net\
    - cov-build --dir cov-int msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform="%platform%"
    - 7z a cov.zip cov-int\*

after_build:
    - cd c:\projects\notepad-plus-plus\
    - ps: >-
        $nppFileName = "Notepad++.$env:PLATFORM.$env:CONFIGURATION.exe"

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Unicode Debug") {
            Push-AppveyorArtifact "PowerEditor\visual.net\Unicode Debug\Notepad++.exe" -FileName "$nppFileName"
        }

        Push-AppveyorArtifact "PowerEditor\visual.net\cov.zip" -FileName "cov.zip"
